splunkPlatform:
  endpoint: "http://10.202.32.241:8088/services/collector/event"
  token: "c7ea588c-8bf3-4ac2-81eb-8fc4845adc72"
  index: "main"
  logsEnabled: true
operator:
  enabled: true
  instrumentation:
    spec:
      java:
        repository: ghcr.io/signalfx/splunk-otel-java/splunk-otel-java
        tag: v2.6.0
      exporter:
        endpoint: http://$(SPLUNK_OTEL_AGENT):4318
